spring:
  application:
    name: cloud-file-storage
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  error:
    include-message: always

