spring:
  application:
    name: cloud-file-storage

  datasource:
    url: jdbc:postgresql://localhost:5433/storage_db
    username: luntik
    password: dispersion

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

minio:
  url: http://localhost:9000
  access-key: ${MINIO_USER}
  secret-key: ${MINIO_PASSWORD}




server:
  port: 8080
  error:
    include-message: always
